const SCREEN_NAMES = {
  TAB_BAR: 'TAB_BAR',
  EVENTS: 'EVENTS',
  FAV_EVENT: 'FAV_EVENT',
  DETAIL_EVENT_STACK: 'DETAIL_EVENT_STACK',
  DETAIL_EVENT: 'DETAIL_EVENT',
} as const

export { SCREEN_NAMES }
